// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/app-footer.vue')['default']
    AppHeader: typeof import('./../src/components/app-header.vue')['default']
    BButton: typeof import('./../src/components/b-button.vue')['default']
    BColorMode: typeof import('./../src/components/b-color-mode.vue')['default']
    BIconButton: typeof import('./../src/components/b-icon-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
